[config]
schemaVersion = "0.0.1"

[package]
namespace = "Quest_play"
name = "MoreItems"
versionNumber = "0.1.0"
description = "Quest_play"
websiteUrl = "https://github.com/Quest-play/MoreItems"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_IL2CPP = "6.0.733"
GatekeeperModding-GKAPI = "0.1.8"
Quest_play-ColorLib = "3.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/MoreItems"

[publish]
repository = "https://thunderstore.io"
communities = ["gatekeeper"]
categories = ["mods"]